services:
  dev-environment:
    build: .
    container_name: dev-env
    volumes:
      - 'home:/root'
    ports:
      - '3001:3000'
      - '60001:22'
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - FOWNER
      - MKNOD
